name: Publish
on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.3
        with:
          persist-credentials: false

      - name: Check Version Changes ↗
        uses: EndBug/version-check@v1.6.0
        id: check

      - name: Setup 🔧
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install ♻
        if: steps.check.outputs.changed == 'true'
        run: npm install

      - name: Publish 🚀
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
